### ISSUE TITLE
Cannot find symbol during interactive linking using new-repl on Windows

### ISSUE THREAD

**Issue by YellPika** [haskell/cabal#5683]
I get the following error on Windows 10:
```
> cabal new-repl --build-depends=ieee754

... GHCi loads ...

Prelude> import Numeric.IEEE
Prelude Numeric.IEEE> infinity
ghc.exe:  | C:\Users\Anthony\AppData\Roaming\cabal\store\ghc-8.6.2\ieee754-0.8.0-7eecc33cf22b0ebf4d3c4dda98cc9f039432a266\lib\libHSieee754-0.8.0-7eecc33cf22b0ebf4d3c4dda98cc9f039432a266.a: unknown symbol `copysign'
ghc.exe: ^^ Could not load 'ieee754zm0zi8zi0zm7eecc33cf22b0ebf4d3c4dda98cc9f039432a266_NumericziIEEE_infinity_closure', dependency unresolved. See top entry above.


ByteCodeLink.lookupCE
During interactive linking, GHCi couldn't find the following symbol:
  ieee754zm0zi8zi0zm7eecc33cf22b0ebf4d3c4dda98cc9f039432a266_NumericziIEEE_infinity_closure
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org
```

This occurs with both cabal-install 2.4.0.0 and HEAD. This does not occur if I install ieee754 into a sandbox and use `cabal repl`. It also works correctly on Ubuntu 18.04 (on both WSL and a full installation), so it looks like a Windows-specific problem.

**Comment by Mistuke** [comment]
hmm this looks like a linker error

```
Tamar@Rage /r> nm -A libHSieee754-0.8.0-7eecc33cf22b0ebf4d3c4dda98cc9f039432a266.a | grep copysign
libHSieee754-0.8.0-7eecc33cf22b0ebf4d3c4dda98cc9f039432a266.a:IEEE.o:                 U copysign
libHSieee754-0.8.0-7eecc33cf22b0ebf4d3c4dda98cc9f039432a266.a:IEEE.o:                 U copysignf
libHSieee754-0.8.0-7eecc33cf22b0ebf4d3c4dda98cc9f039432a266.a:IEEE.o:0000000000000a20 D ieee754zm0zi8zi0zm7eecc33cf22b0ebf4d3c4dda98cc9f039432a266_NumericziIEEE_czucopysign_closure
libHSieee754-0.8.0-7eecc33cf22b0ebf4d3c4dda98cc9f039432a266.a:IEEE.o:0000000000002158 T ieee754zm0zi8zi0zm7eecc33cf22b0ebf4d3c4dda98cc9f039432a266_NumericziIEEE_czucopysign_info
libHSieee754-0.8.0-7eecc33cf22b0ebf4d3c4dda98cc9f039432a266.a:IEEE.o:0000000000000a38 D ieee754zm0zi8zi0zm7eecc33cf22b0ebf4d3c4dda98cc9f039432a266_NumericziIEEE_czucopysignf_closure
libHSieee754-0.8.0-7eecc33cf22b0ebf4d3c4dda98cc9f039432a266.a:IEEE.o:0000000000002358 T ieee754zm0zi8zi0zm7eecc33cf22b0ebf4d3c4dda98cc9f039432a266_NumericziIEEE_czucopysignf_info
libHSieee754-0.8.0-7eecc33cf22b0ebf4d3c4dda98cc9f039432a266.a:double.o:0000000000000000 T copysign
libHSieee754-0.8.0-7eecc33cf22b0ebf4d3c4dda98cc9f039432a266.a:float.o:0000000000000000 T copysignf
```
symbol is there, please report it upstream to `GHC`. add me as `CC` `Phyx-` and I'll take a look soon.

**Comment by Mistuke** [comment]
Closing due to being an upstream linker bug

**Comment by 23Skidoo** [comment]
@Mistuke  Can you please post a link to the relevant upstream ticket?

**Comment by Mistuke** [comment]
@23Skidoo It's https://ghc.haskell.org/trac/ghc/ticket/15894. I have a patch for it and will post it today.

**Comment by Mistuke** [comment]
@YellPika This should be working in the newly released `8.6.3`.
