### ISSUE TITLE
Cabal package not visible to build auto-generated setup.hs

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#11416]
After upgrading cabal from 3.16.0.0 to 3.16.1.0, `cabal test` chokes on the auto-generated `setup.hs`.
```
$ cabal test
Build profile: -w ghc-9.12.2 -O1
In order, the following will be built (use -v for more details):
 - stack-snapshots-0.1.0.0 (test:stack-snapshots-test) (first run)
[1 of 2] Compiling Main             ( dist-newstyle\build\x86_64-windows\ghc-9.12.2\stack-snapshots-0.1.0.0\t\stack-snapsh
ots-test\setup\setup.hs, dist-newstyle\build\x86_64-windows\ghc-9.12.2\stack-snapshots-0.1.0.0\t\stack-snapshots-test\setu
GHC-87110)
         dist-newstyle\build\x86_64-windows\ghc-9.12.2\stack-snapshots-0.1.0.0\t\stack-snapshots-test\setup\setup.hs:2:1: error: [G
HC-87110]
    Could not load module `Distribution.Simple'.
    It is a member of the hidden package `Cabal-3.14.1.0'.
    Perhaps you need to add `Cabal' to the build-depends in your .cabal file.
  |
2 | import Distribution.Simple; main = defaultMain
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

```
The problem is fixed by running `cabal build --enable-tests`.

I guess it would make sense that `cabal test` includes a `cabal build --enable-tests` if things are out-of-date.

**Comment by ulysses4ever** [comment]
@andreasabel this is the only issue marked as regression since 3.16 now. Is there a way to get a reproducer? `stack-snapshots` isn't on Hackage...

**Comment by andreasabel** [comment]
It is here: https://hackage.haskell.org/package/stacker

The reproducer is:
```
cabal get stacker
cd stacker-*
cabal-3.16.0.0 test
cabal-3.16.1.0 test
```
It is essential to create the initial `dist-newstyle` with 3.16.0.0 and then switch to 3.16.1.0.

**Comment by ulysses4ever** [comment]
> It is essential to create the initial dist-newstyle with 3.16.0.0 and then switch to 3.16.1.0.

Oh, plot twist!

If this can’t be reproduced with 3.16.1.0 only, perhaps, the priority will be lowered.

**Comment by andreasabel** [comment]
Well, my description (OP) was:

> After upgrading cabal from 3.16.0.0 to 3.16.1.0, `cabal test` chokes on the auto-generated `setup.hs`.

So, 3.16.1.0 cannot deal with the infra that 3.16.0.0 creates.

This is one of the bugs where cabal displays a lack of resilience.
Maybe cabal was never designed to properly handle outdated build products, so sometimes it does, sometimes not.  
It's like my new prime number theorem I discovered recently: Every odd number is prime.  
It sometimes is correct, sometimes not. :-D

**Comment by sheaf** [comment]
I think this happens any time the `Cabal` version changes in a way that doesn't change `LocalBuildInfo`. For example you can trigger the exact same error by downgrading from `3.16.1.0` to `3.16.0.0`. It isn't anything specific to `3.16`.

Looking at `Distribution.Client.ProjectPlanning.rebuildInstallPlan`, the `rerunIfChanged` actions are keyed by `(projectConfigMonitored, localPackages, progsearchpath)` which does not include any Cabal version, so we conclude we are OK to re-use the old install plan after a minor change to the `Cabal` version (assuming this change preserves `LocalBuildInfo` etc).

That's all OK except that in `Distribution.Client.SetupWrapper` we fall back to the external setup method on a Cabal version mismatch, and we end up trying to compile a `defaultMain` without any dependencies at all, which fails with the error reported here. Another way to say it, we end up trying to build a `SetupNonCustomInternalLib` setup with the external method, which doesn't work.

I will put up a fix, but I think this bug has been around for a long time.
