### PR TITLE
Bump GHC_FOR_QUICK_JOBS to 9.10.3

### LINKED ISSUE #11483: Bump quickjobs to work with ghc-9.10.3
> The other quick jobs are failing now. For the same reason, presumably. A more future-proof solution would be to make them all work with 9.10.

_Originally posted by @ulysses4ever in https://github.com/haskell/cabal/issues/10026#issuecomment-2115725997_

Currently we're running quickjobs with `ghc-9.6.5`:

https://github.com/haskell/cabal/blob/8f648d139bc48300cc9f16e887ca8975da79d1af/.github/workflows/quick-jobs.yml#L18

As per the recommendation in the last bump, please update the version we use for these tests to `ghc-9.10.3`. I don't think we can go higher than that right now as the doctests have a problem with `ghc-9.12.2`.

### PR DESCRIPTION
**Pull request by philderbeast**
Fixes #11483, bump to `ghc-9.10.3` for quickjobs.

I've altered dependencies and fixed warnings in `cabal.meta.project` so that it builds with GHC from `8.4.4`, the minimum we support, up to `9.10.3` without errors.

```
$ cabal build --builddir=dist-newstyle-meta --project-file=cabal.meta.project all --ghc-options=-Werror
```

---

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

File: cabal-dev-scripts/src/AnalyseImports.hs [hunk 1]
```diff
@@ -1,7 +1,7 @@
 {-# LANGUAGE LambdaCase #-}
 module Main (main) where
 
-import Control.Applicative    (liftA2, many, (<|>))
+import Control.Applicative
```
Comment (ffaf1) [inline cabal-dev-scripts/src/AnalyseImports.hs:4]: Are we just importing instances here?

Comment (geekosaur) [reply cabal-dev-scripts/src/AnalyseImports.hs:4]: Wouldn't that be `()`?

Comment (philderbeast) [reply cabal-dev-scripts/src/AnalyseImports.hs:4]: I dropped the import list as a way to avoid this warning (shown here as an error) without using `-XCPP`:

```
$ cabal build --builddir=dist-newstyle-meta --project-file=cabal.meta.project all \
  --ghc-options=-Werror
...
src/AnalyseImports.hs:4:32: error: [-Wunused-imports, Werror=unused-imports]
    The import of ‘liftA2’
    from module ‘Control.Applicative’ is redundant
  |
4 | import Control.Applicative    (liftA2, many, (<|>))
  |       
  ```

Comment (philderbeast) [reply cabal-dev-scripts/src/AnalyseImports.hs:4]: This was the change in `base-4.18.0.0` (`ghc-9.6.1`) from its [changelog](https://hackage.haskell.org/package/base-4.18.0.0/changelog):

> Export liftA2 from Prelude. This means that the entirety of Applicative is now exported from Prelude (CLC proposal #50, the migration guide)

Comment (ffaf1) [reply cabal-dev-scripts/src/AnalyseImports.hs:4]: That makes sense, thanks.
