### ISSUE TITLE
cannot build with ghc-9.12.2 (Variable not in scope: hasLEUpperBound)

### ISSUE THREAD

**Issue by jwaldmann** [haskell/cabal#10916]
```
$ cabal install cabal-install-3.14.2.0

...

[134 of 151] Compiling Distribution.PackageDescription.Check.Target ( src/Distribution/PackageDescription/Check/Target.hs, dist/build/Distribution/PackageDescription/Check/Target.o, dist/build/Distribution/PackageDescription/Check/Target.dyn_o )
src/Distribution/PackageDescription/Check/Target.hs:351:45: error: [GHC-88464]
    Variable not in scope: hasLEUpperBound :: VersionRange -> Bool
    Suggested fix:
      Perhaps use one of these:
        ‘hasUpperBound’ (imported from Distribution.Version),
        data constructor ‘LEUpperBounds’ (imported from Distribution.PackageDescription.Check.Monad),
        ‘hasLowerBound’ (imported from Distribution.Version)
    |
351 |     (checkPVPs (checkDependencyVersionRange hasLEUpperBound) leuck ds)
    |                                             ^^^^^^^^^^^^^^^

src/Distribution/PackageDescription/Check/Target.hs:354:45: error: [GHC-88464]
    Variable not in scope:
      hasTrailingZeroUpperBound :: VersionRange -> Bool
    Suggested fix:
      Perhaps use data constructor ‘TrailingZeroUpperBounds’ (imported from Distribution.PackageDescription.Check.Monad)
    |
354 |     (checkPVPs (checkDependencyVersionRange hasTrailingZeroUpperBound) tzuck ds)
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^

src/Distribution/PackageDescription/Check/Target.hs:357:45: error: [GHC-88464]
    Variable not in scope: hasGTLowerBound :: VersionRange -> Bool
    Suggested fix:
      Perhaps use one of these:
        ‘hasLowerBound’ (imported from Distribution.Version),
        data constructor ‘GTLowerBounds’ (imported from Distribution.PackageDescription.Check.Monad)
    |
357 |     (checkPVPs (checkDependencyVersionRange hasGTLowerBound) gtlck ds)
    |                                             ^^^^^^^^^^^^^^^

```

with
```
$ cabal --version
cabal-install version 3.14.1.1
compiled using version 3.14.1.0 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.12.2
$ uname -a
Linux ...... 6.14.0-63.fc42.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Mar 24 19:53:37 UTC 2025 x86_64 GNU/Linux

```

Build seems to work fine with
```
cabal install cabal-install -w /opt/ghc/ghc-9.10.1/bin/ghc
```

**Comment by geekosaur** [comment]
Note that it's using Cabal 3.12, which is too old for cabal-install 3.14, so it installs Cabal from Hackage instead.

What I don't understand is that, in order to avoid a different incompatibility, we bumped the dependency in cabal-install-3.14.2.0 to require Cabal 3.14.2.0 or later, so the same thing (install from Hackage) should be happening here.

**Comment by geekosaur** [comment]
@Mikolaj opined that the symbols were from Cabal instead of Cabal-syntax on Matrix; if they're from Cabal-syntax then we'll have to hotfix a verbump on that.

**Comment by geekosaur** [comment]
(I think Artem and I are the only ones around this time of night.)

**Comment by ulysses4ever** [comment]
@jwaldmann, thanks a lot for the swift discovery and report. We overlooked one lower bound bump: Cabal should have Cabal-syntax >= 3.14.2. Sadly, I can't do a revision now because Hackage is under maintenance. We'll fix it when it's done, but in the meantime, you can use the `--constraint="Cabal-syntax >= 3.14.2"` option.

**Comment by ulysses4ever** [comment]
Revision is up, so please check it now.

**Comment by ulysses4ever** [comment]
Let's close then. Thanks again for the report!
