### PR TITLE
Cabal 3.14.2 depends on Cabal-syntax at least 3.14.2

### LINKED ISSUE #10916: cannot build with ghc-9.12.2 (Variable not in scope: hasLEUpperBound)
```
$ cabal install cabal-install-3.14.2.0

...

[134 of 151] Compiling Distribution.PackageDescription.Check.Target ( src/Distribution/PackageDescription/Check/Target.hs, dist/build/Distribution/PackageDescription/Check/Target.o, dist/build/Distribution/PackageDescription/Check/Target.dyn_o )
src/Distribution/PackageDescription/Check/Target.hs:351:45: error: [GHC-88464]
    Variable not in scope: hasLEUpperBound :: VersionRange -> Bool
    Suggested fix:
      Perhaps use one of these:
        ‘hasUpperBound’ (imported from Distribution.Version),
        data constructor ‘LEUpperBounds’ (imported from Distribution.PackageDescription.Check.Monad),
        ‘hasLowerBound’ (imported from Distribution.Version)
    |
351 |     (checkPVPs (checkDependencyVersionRange hasLEUpperBound) leuck ds)
    |                                             ^^^^^^^^^^^^^^^

src/Distribution/PackageDescription/Check/Target.hs:354:45: error: [GHC-88464]
    Variable not in scope:
      hasTrailingZeroUpperBound :: VersionRange -> Bool
    Suggested fix:
      Perhaps use data constructor ‘TrailingZeroUpperBounds’ (imported from Distribution.PackageDescription.Check.Monad)
    |
354 |     (checkPVPs (checkDependencyVersionRange hasTrailingZeroUpperBound) tzuck ds)
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^

src/Distribution/PackageDescription/Check/Target.hs:357:45: error: [GHC-88464]
    Variable not in scope: hasGTLowerBound :: VersionRange -> Bool
    Suggested fix:
      Perhaps use one of these:
        ‘hasLowerBound’ (imported from Distribution.Version),
        data constructor ‘GTLowerBounds’ (imported from Distribution.PackageDescription.Check.Monad)
    |
357 |     (checkPVPs (checkDependencyVersionRange hasGTLowerBound) gtlck ds)
    |                                             ^^^^^^^^^^^^^^^

```

with
```
$ cabal --version
cabal-install version 3.14.1.1
compiled using version 3.14.1.0 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.12.2
$ uname -a
Linux ...... 6.14.0-63.fc42.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Mar 24 19:53:37 UTC 2025 x86_64 GNU/Linux

```

Build seems to work fine with
```
cabal install cabal-install -w /opt/ghc/ghc-9.10.1/bin/ghc
```

### PR DESCRIPTION
**Pull request by ulysses4ever**
fix #10916 

---

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Review by ffaf1 — APPROVED** [review]

**Review by Mikolaj — APPROVED** [review]
Thank you.

**Comment by ulysses4ever** [comment]
Looks like we have a plan -- good! I'm thinking about adding something to the Wiki page anyway. The best place I see is:

```
C.3.2 Change the dependency constraints on Cabal-syntax and Cabal to the new version where they are needed in the repo (like cabal-testsuite/cabal-testsuite.cabal and bootstrap/cabal-bootstrap-gen.cabal).
```

I'm not sure why it lists "secondary" packages, which we don't publish, like `cabal-testsuite` and doesn't mention the main packages that we do publish. In any case, this item already has a sublist with one item, and I want to add another one:

```
Sometimes this means updating the lower bounds too, even for minor releases (to avoid issues like [#10916](https://github.com/haskell/cabal/issues/10916) and [#9833](https://github.com/haskell/cabal/issues/9833)).

Thouths?
```

**Comment by geekosaur** [comment]
I think the ones it lists are the ones that are usually forgotten even in major versions, whereas this case only happens when we have unexpected API changes in minor versions.

**Comment by ffaf1** [comment]
Should this be forward ported to `master`?

**Comment by ulysses4ever** [comment]
@ffaf1 I was thinking about it. It's not clear to me that it should. Master has 3.15 everywhere, I think. When 3.16 will be cut, we must make sure that dependencies are handled accordingly. But I'm not sure we want 3.14.2 for version bound on master.
