### ISSUE TITLE
Cabal-1.8.0.2 doesn't build on x86_64, GHC 6.10.4

### ISSUE THREAD

**Issue by bos** [haskell/cabal#613]
(Imported from [Trac #620](http://hackage.haskell.org/trac/hackage/ticket/620), reported by Ashley Yakeley on 2009-12-22)

<pre class="wiki">$ cabal install 'Cabal &gt;= 0.8'
</pre>...

<pre class="wiki">Linking /tmp/Cabal-1.8.0.214524/Cabal-1.8.0.2/dist/setup/setup ...
/usr/local/lib/ghc-6.10.4/base-4.1.0.0/libHSbase-4.1.0.0.a(PrelIOUtils.o): In function `__hscore_d_name':
PrelIOUtils.c:(.text+0x1c0): multiple definition of `__hscore_d_name'
/home/ashley/.cabal/lib/unix-2.4.0.0/ghc-6.10.4/libHSunix-2.4.0.0.a(dirUtils.o):dirUtils.c:(.text+0x0): first defined here
/usr/local/lib/ghc-6.10.4/base-4.1.0.0/libHSbase-4.1.0.0.a(PrelIOUtils.o): In function `__hscore_free_dirent':
PrelIOUtils.c:(.text+0x4f0): multiple definition of `__hscore_free_dirent'
/home/ashley/.cabal/lib/unix-2.4.0.0/ghc-6.10.4/libHSunix-2.4.0.0.a(dirUtils.o):dirUtils.c:(.text+0x10): first defined here
/home/ashley/.cabal/lib/unix-2.4.0.0/ghc-6.10.4/libHSunix-2.4.0.0.a(IO.o): In function `sk63_info':
(.text+0x30c4): undefined reference to `fcntl_read'
/home/ashley/.cabal/lib/unix-2.4.0.0/ghc-6.10.4/libHSunix-2.4.0.0.a(IO.o): In function `sk6A_info':
(.text+0x31f0): undefined reference to `fcntl_write'
/home/ashley/.cabal/lib/unix-2.4.0.0/ghc-6.10.4/libHSunix-2.4.0.0.a(IO.o): In function `sk8h_info':
(.text+0x36cc): undefined reference to `fcntl_read'
/home/ashley/.cabal/lib/unix-2.4.0.0/ghc-6.10.4/libHSunix-2.4.0.0.a(IO.o): In function `sl4O_info':
(.text+0x3a52): undefined reference to `fcntl_lock'
/home/ashley/.cabal/lib/unix-2.4.0.0/ghc-6.10.4/libHSunix-2.4.0.0.a(IO.o): In function `sl6S_info':
(.text+0x3cc2): undefined reference to `fcntl_lock'
/home/ashley/.cabal/lib/unix-2.4.0.0/ghc-6.10.4/libHSunix-2.4.0.0.a(IO.o): In function `sl9I_info':
(.text+0x402a): undefined reference to `fcntl_lock'
collect2: ld returned 1 exit status
cabal: Error: some packages failed to install:
Cabal-1.8.0.2 failed during the configure step. The exception was:
exit: ExitFailure 1
</pre><pre class="wiki">$ uname -a
Linux glastonbury 2.6.31-17-generic #54-Ubuntu SMP Thu Dec 10 17:01:44 UTC 2009 x86_64 GNU/Linux
</pre>
