### ISSUE TITLE
Cannot install HEAD cabal-install

### ISSUE THREAD

**Issue by goldfirere** [haskell/cabal#6595]
**Describe the bug**

I cannot install the latest `cabal-install`.

**To Reproduce**

* If I clone the repo, navigate to the `cabal-install` directory, and say `cabal install`, I get a bunch of sdist files written and then `cabal: filepath wildcard 'README.md' does not match any files.`.
* If I try to use `bootstrap.sh`, I get the following after a bunch of other output:

```
Distribution/Simple/Program/HcPkg.hs:1:1: error:
    `gcc' failed in phase `C pre-processor'. (Exit code: 1)
  |
1 | {-# LANGUAGE CPP               #-}
  | ^

Error during cabal-install bootstrap:
Compiling the Setup script failed.
```

So I'm stuck. :(

**Expected behavior**

I expect there to be some way to install `cabal`.

**System information**
 - MacOS 10.13.6
 - GHC 8.8.1

**Comment by bgamari** [comment]
I'm not surprised that `cabal-install` doesn't currently build with GHC 8.10 without a bit of work. I would expect that you need to at very least pass `--allow-newer` to your `cabal install` command-line. It's also possible that you will need to use [head.hackage](https://gitlab.haskell.org/ghc/head.hackage/). It's even possible that you will need to adapt the source.

However, I do wonder why you need to build `cabal-install` with GHC 8.10 at all. Why not build `cabal-install` with a released compiled (e.g. 8.8) and then use it with 8.10 (using the `-w` flag to specify the compiler).

**Comment by goldfirere** [comment]
Sorry -- I should have clarified: when I tried installing the HEAD version of cabal-install, I was on GHC 8.8. Ditto bootstrap.sh. I'll update the description.

**Comment by bgamari** [comment]
Hmmm, this is surprising. I can build `cabal-install` locally without any trouble. Is this Darwin? Does `cabal v2-build` work?

Alternatively, if you hop on IRC I'd be happy to try helping.

**Comment by phadej** [comment]
`cabal: filepath wildcard 'README.md' does not match any files.` error suggests that `cabal-install` used is some older version from `3.2` branch.

That issue is fixed in https://github.com/haskell/cabal/commit/4af71790b06df999ef8c61ff653221b69cdfdd9d

Please try to `cabal build install` with some stable release (i.e. `cabal-install-3.0.0.0`).

**Comment by goldfirere** [comment]
My checkout has 4af7179; it's on the `master` branch, at commit f8ad7bb43eaaee290a24587215c5ae1c47b3f83b. So I don't think https://github.com/haskell/cabal/issues/6595#issuecomment-602237745 applies.

Oh wait -- maybe you are talking not about the cabal-install I wish to install, but the cabal-install on my system. It is indeed a stock install of 3.0.0.0. (Sorry for not including this in my original report -- I was too fixated on trying to use some `cabal` with GHC HEAD.)

**Comment by phadej** [comment]
The breakage commit f2b2ab7c11541fecef81bd9f954d7ff33002c485 is unfortunately in `3.0.0.0`. I'm trying to reach people who are able to do proper releases. I'm really sorry that there are no releases since.

Until then you could grab artifacts from our CI, at https://github.com/haskell/cabal/actions/runs/39422172 for 3.2 branch or at https://github.com/haskell/cabal/actions/runs/60507399 for master.

**Comment by phadej** [comment]
Argh.

```
Wrote tarball sdist to
/code/shared-haskell/cabal/dist-newstyle/sdist/Cabal-3.3.0.0.tar.gz
Wrote tarball sdist to
/code/shared-haskell/cabal/dist-newstyle/sdist/cabal-testsuite-3.tar.gz
Wrote tarball sdist to
/code/shared-haskell/cabal/dist-newstyle/sdist/cabal-install-3.3.0.0.tar.gz
Wrote tarball sdist to
/code/shared-haskell/cabal/dist-newstyle/sdist/solver-benchmarks-3.tar.gz
Wrote tarball sdist to
/code/shared-haskell/cabal/dist-newstyle/sdist/Cabal-quickcheck-3.3.0.0.tar.gz
cabal: filepath wildcard 'README.md' does not match any files.

```

Full output would told where's the culprit. Silly me.

**Comment by goldfirere** [comment]
OK. Let me see if I can summarize the state of play:

- The released cabal-install 3.0.0.0 has the bug in question (and there are no releases since).

- The bug prevents installing a newer version of cabal-install.

- So I have to pretend I don't have `cabal` at all and just download a binary to get a later `cabal-install`.

If/when a new version of cabal-install is uploaded to Hackage, will cabal-install 3.0.0.0 be able to install it? Or will everyone have to download binaries to upgrade?

Thanks for your help here!

**Comment by phadej** [comment]
> If/when a new version of cabal-install is uploaded to Hackage, will cabal-install 3.0.0.0 be able to install it? Or will everyone have to download binaries to upgrade?

No. What fails is making the `.tar.gz` from local sources to be installed. But you get one from Hackage, so `cabal install cabal` should work then.

In fact, I'm working towards functionality that we can actually test the latter case more directly.
