### ISSUE TITLE
Generated setup.hs doesn't build with ghc 8.2

### ISSUE THREAD

**Issue by erikd** [haskell/cabal#4436]
Trying to build [HsOpenSSL](https://github.com/vshabanov/HsOpenSSL.git) with ghc 8.2 and I get this error:
```
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )

dist/setup/setup.hs:73:18: error:
    Not in scope: data constructor ‘FlagName’
   |
73 |           go (x@(FlagName n, _):xs)
   |                  ^^^^^^^^
```
The file `dist/setup/setup.hs` is a generated file. Not sure if this is something that should be fixed in cabal or in the ghc 8.2 release candidate.

My cabal version is:
```
> cabal --version
cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library 
```
which seems to be the latest on Hackage.

**Comment by cocreature** [comment]
I don’t think this is an error in cabal or GHC. The problem is the [`Setup.hs` file](https://github.com/vshabanov/HsOpenSSL/blob/master/Setup.hs) in `HsOpenSSL`.

**Comment by erikd** [comment]
You are correct @cocreature . Closing this.

**Comment by erikd** [comment]
Actually, not sure. Yes, its in the `Setup.hs` file, but this is a breaking change caused by the new ghc version.

**Comment by 23Skidoo** [comment]
See https://github.com/haskell/cabal/blob/master/Cabal/changelog#L59.

**Comment by erikd** [comment]
Ok, so i have a fix to the `Setup.hs` file, but that fails to build with ghc 8.0 or earlier.

Can I use CPP in a `Setup.hs`, Will the cabal version macros be available?

**Comment by cocreature** [comment]
Yes you can, I’ve added something like
```
#if !MIN_VERSION_Cabal(2,0,0)
mkVersion ver = Version ver []
versionNumbers = versionBranch
mkFlagName = FlagName
#endif
```
to my Cabal files.

**Comment by erikd** [comment]
This `Setup.hs` file has other stuff that breaks with CPP like:
```
notFound =
    "Can't find OpenSSL library,\n\
    \install it via 'brew install openssl' or 'port install openssl'\n\
    \or use --extra-include-dirs= and --extra-lib-dirs=\n\
    \to specify location of installed OpenSSL library."
```

**Comment by cocreature** [comment]
That’s a general problem with CPP and multiline strings. The easiest solution is to use `unlines`.

**Comment by 23Skidoo** [comment]
Consider also adding a `custom-setup` stanza.

**Comment by 23Skidoo** [comment]
```
#if !MIN_VERSION_Cabal(2,0,0)
```

Note that without `custom-setup` (which is only supported by `cabal-install` >= 1.24) you need a recent GHC (>=8.0.1, I think) for this to work.

**Comment by 23Skidoo** [comment]
Try 

```
#ifdef MIN_VERSION_Cabal
#if MIN_VERSION_Cabal(2,0,0)
#define MIN_VERSION_Cabal_2_0_0
#endif
#endif

...
#if MIN_VERSION_Cabal_2_0_0
...
#else
...
#endif
```

May still break in the rare case when someone uses Cabal >= 2.0 with old GHC and `cabal-install`.

**Comment by erikd** [comment]
I ended up using:
```
#if __GLASGOW_HASKELL__ >= 802
...
```
