### ISSUE TITLE
`Cabal-syntax`'s dependency on `bytestring` is too loose

### ISSUE THREAD

**Issue by mniip** [haskell/cabal#11316]
`Cabal-syntax` declares a dependency on `bytestring >=0.10`, however building `Cabal-syntax >=3.8.1.0 && <=3.10.3.0` against `bytestring-0.10.6.0` using GHC 8.0 or GHC 8.2 fails:
```
src/Distribution/PackageDescription/FieldGrammar.hs:798:22: error:
    • No instance for (Semigroup FieldName) arising from a use of ‘<>’
    • In the second argument of ‘($)’, namely ‘" \\ " <> n’
      In the expression: BS8.putStrLn $ " \\ " <> n
      In the first argument of ‘sequence_’, namely
        ‘[BS8.putStrLn $ " \\ " <> n |
            n <- nub
                   $ sort
                       $ mconcat
                           [fieldGrammarKnownFieldList packageDescriptionFieldGrammar,
                            fieldGrammarKnownFieldList $ libraryFieldGrammar LMainLibName,
                            fieldGrammarKnownFieldList $ executableFieldGrammar "exe", ....]]’
    |
798 |     [ BS8.putStrLn $ " \\ " <> n
    |                      ^^^^^^^^^^^
```

The reason is that during the [Semigroup/Monoid proposal](https://gitlab.haskell.org/haskell/prime/-/wikis/libraries/proposals/semigroup-monoid), in GHC 8.0 and 8.2, `base` does have a `Semigroup` class (and a `<>` operator), but it is not yet a superclass of `Monoid`, meaning datatypes that are not yet aware of the migration will define a `Monoid` instance but not a `Semigroup` instance.

A `Semigroup ByteString` instance was only added in `bytestring-0.10.8.0`, and so while `bytestring-0.10.6.0` builds fine on GHC 8.0 and 8.2, you cannot use `<>` with it.

`Cabal-syntax >=3.12.0.0` no longer support GHC 8.0 and 8.2, so the issue is not reproducible with them, but a hackage revision for older versions is still needed.

**Comment by mniip** [comment]
This issue also manifests with `Cabal >=3.6.0.0 && <=3.6.3.0` where this code used to live prior to being split off into `Cabal-syntax`.

**Comment by geekosaur** [comment]
Metadata updated.
