### ISSUE TITLE
Error while building cabal with profiling with new-build

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#3827]
I tried to build cabal HEAD with GHC 8.0.1:
`cabal new-build cabal --enable-profiling --profiling-detail=all-functions`

```
[ 18 of 125] Compiling Distribution.Client.ParseUtils ( Distribution/Client/ParseUtils.hs, /home/kristen/other/haskell/cabal/dist-newstyle/build/x86_64-linux/ghc-8.0.1/cabal-install-1.25.0.0/build/cabal/cabal-tmp/Distribution/Client/ParseUtils.p_o )
[ 19 of 125] Compiling Distribution.Client.Compat.Semaphore ( Distribution/Client/Compat/Semaphore.hs, /home/kristen/other/haskell/cabal/dist-newstyle/build/x86_64-linux/ghc-8.0.1/cabal-install-1.25.0.0/build/cabal/cabal-tmp/Distribution/Client/Compat/Semaphore.p_o )

Distribution/Client/Compat/Semaphore.hs:10:1: error:
    Failed to load interface for ‘Control.Concurrent.STM’
    Perhaps you haven't installed the profiling libraries for package ‘stm-2.4.4.1@stm-2.4.4.1-d538ed94796380538f3e84756206fdbe52eac32676d556a60f366bef510df939’?
    Use -v to see a list of the files searched for.
```

The full log is at https://gist.github.com/grayjay/c211f03577621887f4363bda88b6a3c3

I ran git bisect and found that it started in 4100c376d5a0d01887fd5eff13fef80ae6447abc.

**Comment by ezyang** [comment]
Ah. I know what the bug is :)
