### ISSUE TITLE
"#! /usr/bin/env cabal" seems broken on windows

### ISSUE THREAD

**Issue by AndreasPK** [haskell/cabal#5775]
The same input file works on linux with cabal-2.4.

I've built cabal-install today from HEAD to make sure this wasn't an solved issue.

Input file
```
#! /usr/bin/env cabal
{- cabal:
build-depends: base ^>= 4.0
-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE ScopedTypeVariables #-}

import Prelude

main :: IO ()
main = return()
```

Console output.
```
$ cabal cabTest.hs
Resolving dependencies...
Build profile: -w ghc-8.4.3 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (exe:script) (first run)
Configuring executable 'script' for fake-package-0..
Preprocessing executable 'script' for fake-package-0..
Building executable 'script' for fake-package-0..
[1 of 1] Compiling Main             ( Main.hs, C:\ghc\msys64\tmp\cabal-repl.-28296\dist-newstyle\build\x86_64-windows\ghc-8.4.3\fake-package-0\x\script\build\script\script-tmp\Main.o )

Main.hs:7:1: error:
    Could not find module `Prelude'
    Use -v to see a list of the files searched for.
  |
7 | import Prelude
  | ^^^^^^^^^^^^^^
```

**Comment by 23Skidoo** [comment]
/cc @typedrat

Don't we have a test case for this?

**Comment by hvr** [comment]
@AndreasPK could you verify whether PR #5790 fixes this?

**Comment by AndreasPK** [comment]
The PR fixed it.

**Comment by phadej** [comment]
This is not fixed, see https://github.com/haskell/cabal/pull/6132

**Comment by phadej** [comment]
tests pass, closing. Sorry for the noise.
