### ISSUE TITLE
Cabal 3.4 rc3 fails to build with bytestring-0.11.0.0-rc1

### ISSUE THREAD

**Issue by vmchale** [haskell/cabal#7079]
With the following in my `cabal.project`

```
source-repository-package
  type: git
  location: https://github.com/haskell/bytestring
  tag: 0.11.0.0-rc1

source-repository-package
  type: git
  location: https://github.com/haskell/cabal.git
  tag: Cabal-3.4.0.0-rc3
  subdir: Cabal

allow-newer:
  *:bytestring
```

I get

```
Distribution/Utils/Structured.hs:90:1: error:
    Could not load module ‘Data.ByteString.Lazy.Builder’
    It is a member of the hidden package ‘bytestring-0.10.10.0’.
    Perhaps you need to add ‘bytestring’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
90 | import qualified Data.ByteString.Lazy.Builder as Builder
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

(using GHC 8.10.2)

This may hold up GHC 9.x working with Cabal.

**Comment by phadej** [comment]
The 679b78bb04a21f938faf0cae23ffc0edb50cb6c0 is in `Cabal-3.4.0.0-rc3`. I'm confused.

**Comment by phadej** [comment]
No response. Closing.
