### PR TITLE
Allow minor Cabal version bumps without recompiling

### LINKED ISSUE #11416: Cabal package not visible to build auto-generated setup.hs
After upgrading cabal from 3.16.0.0 to 3.16.1.0, `cabal test` chokes on the auto-generated `setup.hs`.
```
$ cabal test
Build profile: -w ghc-9.12.2 -O1
In order, the following will be built (use -v for more details):
 - stack-snapshots-0.1.0.0 (test:stack-snapshots-test) (first run)
[1 of 2] Compiling Main             ( dist-newstyle\build\x86_64-windows\ghc-9.12.2\stack-snapshots-0.1.0.0\t\stack-snapsh
ots-test\setup\setup.hs, dist-newstyle\build\x86_64-windows\ghc-9.12.2\stack-snapshots-0.1.0.0\t\stack-snapshots-test\setu
GHC-87110)
         dist-newstyle\build\x86_64-windows\ghc-9.12.2\stack-snapshots-0.1.0.0\t\stack-snapshots-test\setup\setup.hs:2:1: error: [G
HC-87110]
    Could not load module `Distribution.Simple'.
    It is a member of the hidden package `Cabal-3.14.1.0'.
    Perhaps you need to add `Cabal' to the build-depends in your .cabal file.
  |
2 | import Distribution.Simple; main = defaultMain
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

```
The problem is fixed by running `cabal build --enable-tests`.

I guess it would make sense that `cabal test` includes a `cabal build --enable-tests` if things are out-of-date.

### PR DESCRIPTION
**Pull request by sheaf**
Fix for #11416: we now don't store the specific Cabal library version used to provide the Setup CLI, which allows us to re-use an install plan made with another Cabal library version that is still compatible (e.g. across a minor version bump).

No test, as this requires building with two different versions of `cabal-install` in CI a minor version apart, which seems tricky to achieve. I checked locally and the change does fix the reported reproducer.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog)**

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added: no, see reason above.

---

## QA notes

We want to ensure that we can do a build, then do a minor version change to `cabal-install`, then build again, without the error in #11416 and also without recompilation.

Manual QA steps:

  - Create a package with `build-type: Simple` which has a testsuite component. Any package at all will do.
  - Run `cabal test` for this package, with the `cabal-install` built with this patch.
  - Do a minor version bump to `cabal-install` and its `Cabal` library and rebuild `cabal-install`.
  - Re-run `cabal test`: it should succeed and not cause recompilation.

### CODE REVIEW

**Review by zlonast — APPROVED** [review]

**Review by Mikolaj — APPROVED** [review]
Thank you. Please set the merge_me label.

**Review by andreasabel — COMMENTED** [review]
I have been asked to review this PR since I reported the issue.
I am not familiar with the internal workings of Cabal so I cannot comment on the implementation of the solution.
What I could do here is to verify that the test case covers the issue.
But there is no test case included here.

**Comment by sheaf** [comment]
> I have been asked to review this PR since I reported the issue. I am not familiar with the internal workings of Cabal so I cannot comment on the implementation of the solution. What I could do here is to verify that the test case covers the issue. But there is no test case included here.

The problem is that reproducing involves building a package with two different versions of `cabal-install`, while all of the testsuite framework only works with a single version of `cabal-install`.

**Comment by andreasabel** [comment]
> The problem is that reproducing involves building a package with two different versions of `cabal-install`, while all of the testsuite framework only works with a single version of `cabal-install`.

That's fine.  Asking for a new test framework that would cover such cases would be feature creep.  So we have to confine ourselves anecdotal testing here (which I trust you have performed).

**Comment by ffaf1** [comment]
> The problem is that reproducing involves building a package with two different versions of cabal-install, while all of the testsuite framework only works with a single version of cabal-install.

Yes, those are [QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes).

Is it feasible to add them?  That way, other cabal devs could test on their enviroment.

**Comment by sheaf** [comment]
> Is it feasible to add them? That way, other cabal devs could test on their enviroment.

I added QA notes to the OP. Please let me know if what I wrote isn't sufficient.

**Comment by ffaf1** [comment]
Many thanks!  I ran your instructions and indeed it does not choke as in #11416.

Sadly, this _cannot_ be backported to `3.18` as it breaks API.

**Comment by Mikolaj** [comment]
@sheaf: Or maybe there's a way to fix this without breaking the API?

**Comment by sheaf** [comment]
> @sheaf: Or maybe there's a way to fix this without breaking the API?

Fundamentally the issue is that, without this patch, `cabal-install` is serialising to the on-disk cache the exact version of `Cabal` it was linked against. The fix needs it to stop doing that which changes the binary instance of `LocalBuildInfo`.

It would be possible to continue to write this information to disk but have some logic to carefully ignore it but that seems worse in terms of maintainability. Given that this is not a regression I don't think it's a huge problem that the fix does not get backported.

**Comment by Mikolaj** [comment]
@sheaf: thank you. @ffaf1: I support your decision not to backport this one. Let's keep the release note about it, maybe also in Release Notes for 3.18.2.0, and move on. After all, it's not a regression in 3.18 nor even in 3.16, I think.
