### PR TITLE
Correctly propagate profiling for ALL library dependencies.

### LINKED ISSUE #3827: Error while building cabal with profiling with new-build
I tried to build cabal HEAD with GHC 8.0.1:
`cabal new-build cabal --enable-profiling --profiling-detail=all-functions`

```
[ 18 of 125] Compiling Distribution.Client.ParseUtils ( Distribution/Client/ParseUtils.hs, /home/kristen/other/haskell/cabal/dist-newstyle/build/x86_64-linux/ghc-8.0.1/cabal-install-1.25.0.0/build/cabal/cabal-tmp/Distribution/Client/ParseUtils.p_o )
[ 19 of 125] Compiling Distribution.Client.Compat.Semaphore ( Distribution/Client/Compat/Semaphore.hs, /home/kristen/other/haskell/cabal/dist-newstyle/build/x86_64-linux/ghc-8.0.1/cabal-install-1.25.0.0/build/cabal/cabal-tmp/Distribution/Client/Compat/Semaphore.p_o )

Distribution/Client/Compat/Semaphore.hs:10:1: error:
    Failed to load interface for ‘Control.Concurrent.STM’
    Perhaps you haven't installed the profiling libraries for package ‘stm-2.4.4.1@stm-2.4.4.1-d538ed94796380538f3e84756206fdbe52eac32676d556a60f366bef510df939’?
    Use -v to see a list of the files searched for.
```

The full log is at https://gist.github.com/grayjay/c211f03577621887f4363bda88b6a3c3

I ran git bisect and found that it started in 4100c376d5a0d01887fd5eff13fef80ae6447abc.

### PR DESCRIPTION
**Pull request by ezyang**
Previously, we were only doing library dependencies of the libraries,
which is wrong if we try to profile an executable.

Fixes #3827. CC @grayjay.

Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

File: cabal-install/Distribution/Client/ProjectPlanning.hs [hunk 1]
```diff
@@ -1610,7 +1610,7 @@ instance IsNode LibDepSolverPlanPackage where
     type Key LibDepSolverPlanPackage = SolverId
     nodeKey = nodeKey . unLibDepSolverPlanPackage
     nodeNeighbors (LibDepSolverPlanPackage spkg)
-        = ordNub $ CD.libraryDeps (resolverPackageLibDeps spkg)
```
Comment (23Skidoo) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: So the haddock comment and maybe the type name also needs to be updated?

**Comment by 23Skidoo** [comment]
Looks like you forgot to update `extra-source-files`.

**Comment by dcoutts** [comment]
@ezyang so why is this the correct fix? (Perhaps it's just a matter of confusing names.)

Non-setup deps sounds like it would be library-deps and executable-deps (deps of all normal components). Clearly we want the library-deps of all normal components. You say in #3827 that the current code only returns the lib deps of the libraries, rather than the lib deps of the libs + exes (+ test/bench etc)

**Comment by ezyang** [comment]
The root cause is a confusing overloading of the term "library dependencies". It can mean two things: a dependency on a library (elabLibDependencies) or it can be the dependencies of the library of a package (CD.libraryDeps). Let's try to come up with a different name for one of these.

**Comment by grayjay** [comment]
It worked for me.  Thanks!
