### ISSUE TITLE
cabal installation failed with compiler error

### ISSUE THREAD

**Issue by badger1961** [haskell/cabal#4931]
Hello

I use HaskellPlatform 8.2.1
I tried to install current version of cabal, using command : 
cabal.exe  --http-transport=powershell  install cabal-install. and I observe the following issue

This is tail of  build log
```
[112 of 140] Compiling Distribution.Client.Configure ( Distribution\Client\Configure.hs, dist\build\cabal\cabal-tmp\Distribution\Client\Configure.o )                                                     
[113 of 140] Compiling Distribution.Client.Sandbox.PackageEnvironment ( Distribution\Client\Sandbox\PackageEnvironment.hs, dist\build\cabal\cabal-tmp\Distribution\Client\Sandbox\PackageEnvironment.o )  
[114 of 140] Compiling Distribution.Client.ProjectConfig.Legacy ( Distribution\Client\ProjectConfig\Legacy.hs, dist\build\cabal\cabal-tmp\Distribution\Client\ProjectConfig\Legacy.o )                    
[115 of 140] Compiling Distribution.Client.ProjectConfig ( Distribution\Client\ProjectConfig.hs, dist\build\cabal\cabal-tmp\Distribution\Client\ProjectConfig.o )                                         
                                                                                                                                                                                                          
Distribution\Client\ProjectConfig.hs:108:23: error:
    Module `Distribution.Verbosity' does not export `modifyVerbosity'
    |
108 |          ( Verbosity, modifyVerbosity, verbose )
    |                       ^^^^^^^^^^^^^^^
cabal: Leaving directory 'C:\Users\agorlov\AppData\Local\Temp\cabal-tmp-15048\cabal-install-2.0.0.1'
cabal.exe: Error: some packages failed to install:
cabal-install-2.0.0.1-IIDkvf2x92pEDuQyB9IAjO failed during the building phase.
The exception was:
ExitFailure 1
```

Could you please help me to resolve this issue?

Thank you in advance 
Alex

**Comment by badger1961** [comment]
I use Windows 10 64 bits

**Comment by 23Skidoo** [comment]
Looks like `modifyVerbosity` was added in `Cabal-2.0.1.0`. I updated `cabal-install`'s package description on Hackage, please run `cabal update` and retry.

**Comment by hvr** [comment]
I have been revising the cabal file as well (it took forever for `cabal-install-2.0.0.1` to compile with `Cabal-2.0.1.0` on GHC 8.2.1 to verify this worked for sure... :-)

**Comment by 23Skidoo** [comment]
@hvr Can you also push those changes to the `2.0` branch?

**Comment by hvr** [comment]
@23Skidoo if I push the `base >= 4.5` one, iirc it'll fail the GHC 7.4 job there; shall I mark it allowed to fail?

**Comment by 23Skidoo** [comment]
Why do we need base >= 4.5?

**Comment by hvr** [comment]
@23Skidoo It's not so much that we need `base >= 4.6` but rather that `cabal-install` makes use of some language extensions that became available only in GHC 7.6 (iirc LambdaCase in one or two modules)

**Comment by 23Skidoo** [comment]
@hvr Why would the GHC 7.4 job fail then -- I see that that configuration is built with `CABAL_LIB_ONLY=YES`?

**Comment by hvr** [comment]
@23Skidoo IIRCL because `cabal.project` unconditionally includes `cabal-install`, and thus the solver has to find a plan for GHC 7.4 including `cabal-install`, even if it isn't built.

**Comment by 23Skidoo** [comment]
I think we can work around this with --allow-newer.

**Comment by hvr** [comment]
> I think we can work around this with --allow-newer.

...you mean `--allow-older` ;-)

**Comment by 23Skidoo** [comment]
Yep, or I guess we can just have a separate `cabal.project` file for 7.4.

**Comment by badger1961** [comment]
the command cabal update hangs in my case without any information. If I try to use 
**C:\toolchains\HaskellPlatform\8.2.1\lib\extralibs\bin>cabal.exe  --http-transport=powershell  update**  
I observe the following error message. 

Downloading the latest package list from hackage.haskell.org                                          
dieVerbatim: user error (cabal.exe: Failed to download                                                
http://objects-us-west-1.dream.io/hackage-mirror/01-index.tar.gz : No Status                          
Code could be parsed from response: An exception occurred during a WebClient                          
request.                                                                                              
)                                                          

My workplace is behind a proxy. But I don't found correct rule to work with proxy. I try to add proxy definition to cabal config something like 
export http_proxy=http://xxx.xxx.xx:9999
but without success.

**Comment by gbaz** [comment]
if you do use the powershell transport, it will use the system proxy set by windows, typically via the "internet settings" accessible from internet explorer.
