### ISSUE TITLE
CI fails linking package resolve with ubuntu-latest (which is 22.04) but works fine with 20.04

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#8630]
The temporary fix is at https://github.com/haskell/cabal/pull/8629 and in a comment below I'm pasting a lightning debugging session with @bgamari and others that did not reveal the culprit (most probably something specific to the github Ubuntu container, but if so others should report soon, too).

May just be a cache key not containing ubuntu version: TODO. Edit: indeed, the key seems to ignore OS version, but resetting cache does not help in this case.

Sample failed run: https://github.com/haskell/cabal/actions/runs/3634604652/jobs/6132858557

Edit: a sample bit of the CI log, because the transcript below is undreadable:

> /home/runner/.cabal/store/ghc-9.4.2/resolv-0.1.2.0-6cbf3d0fda87d8c3376996313e637e0218569df76d4a25fe7ed2b1b689ee7dc9/lib/libHSresolv-0.1.2.0-6cbf3d0fda87d8c3376996313e637e0218569df76d4a25fe7ed2b1b689ee7dc9.a(FFI.o):ghc_10.c:function ghczuwrapperZC3ZCresolvzm0zi1zi2zi0zm6cbf3d0fda87d8c3376996313e637e0218569df76d4a25fe7ed2b1b689ee7dc9ZCNetworkziDNSziFFIZChszureszuquery: error: undefined reference to '__res_nquery'

**Comment by Mikolaj** [comment]
Artem
setup-depends there is pure magic, it has a comment to that effect I think
mikolaj
oh yes, the one nobody understands, but nobody can violate without breakage
bgamari@bgamari:matrix.org
yes, that comment is quite mysterious
I have dropped the constraints and I am now building
Today
mikolaj
heh, I've actually wrote one line of the comment, but then I repressed the memory
bgamari@bgamari:matrix.org
strangely integration-tests2 passes for me
mikolaj
let me make sure it was failing with GHC 9.2 as well
unfortunately, I can't identify which failed jobs have been with GHC 9.2
...easily
got it
https://github.com/haskell/cabal/actions/runs/3633669946/jobs/6130945839
[Update GHC in CI from 9.4.2 to 9.4.3 and try to run it last · haskell/cabal@b10d140](https://github.com/haskell/cabal/actions/runs/3633669946/jobs/6130945839) - GitHub
Official upstream development repository for Cabal and cabal-install - Update GHC in CI from 9.4.2 to 9.4.3 and try to run it last · haskell/cabal@b10d140
here, only integration-tests2 failed
so, no reproduction
I mean, negative reproduction
ghc-9.2.3
actually long-tests failed, too; just a different display than with GHC 9.4, but the same error
bgamari@bgamari:matrix.org
I'll try long-tetss
incredibly that too works for me

mikolaj
ok, thanks a lot; it must be something else than GHC
bgamari@bgamari:matrix.org
mikolaj: if you can reproduce this failure perhaps you could run ghc-pkg describe resolv?
mikolaj
will do
the commandline we use is CMD="$($CABALPLANLISTBIN cabal-install:test:integration-tests2) -j1 --hide-successes --with-ghc=$HC", so nothing special
perhaps our CI cache got stale or just some random local tweak by github
geekosaur@geekosaur:libera.chat
that's git failing, I think because of a security thing
mikolaj
bgamari: I'm sorry for taking your time
bgamari@bgamari:matrix.org
quite alright
geekosaur@geekosaur:libera.chat
https://vielmetti.typepad.com/logbook/2022/10/git-security-fixes-lead-to-fatal-transport-file-not-allowed-error-in-ci-systems-cve-2022-39253.html
[git security fixes lead to "fatal: transport 'file' not allowed" error in CI systems; CVE-2022-39253](https://vielmetti.typepad.com/logbook/2022/10/git-security-fixes-lead-to-fatal-transport-file-not-allowed-error-in-ci-systems-cve-2022-39253.html) - Logbook
If you are running a CI system that uses git to check out software for builds, and if that environment uses "git submodule add" to bring in files from the filesystem, then you might be affected by
among othyer references thereto
mikolaj
oh, but that's test running commandline; irrelevant; it fails at link tiem
bgamari@bgamari:matrix.org
yes, that's right
mikolaj
and commandline for building is plain vanilla
bgamari@bgamari:matrix.org
yes, I'm generally very confused
I can only guess that this is due to image differences
this is a fresh container, afterall
mikolaj
if anybody else reports this to you; please remember to get in touch :)
I wouldn't be surprised if haskell-ci was affected, too, for people running the new container
bgamari@bgamari:matrix.org
I'm very curious to see that ghc-pkg output
seeing ghc -v3 output would also be useful
mikolaj
how do I ask ghc for -v3 through cabal?
bgamari@bgamari:matrix.org
I wish there was an easy way
consider this a feature request ;)
mikolaj
got it :)
bgamari@bgamari:matrix.org
I generally add ghc-options: -v3 to my project file
mikolaj
ok, will do; and just ghc-pkg or some parameters?
bgamari@bgamari:matrix.org
ghc-pkg describe resolv
mikolaj
ok
Double-hammer CI fix (Ubuntu downgrade and removal of GHC 9.4.3) will finish soon, so I will try 1.5 hammer (Ubuntu and GHC down to 9.4.2) with the extra instrumentation
and next up will be CI cache reset
mikolaj
actually, GHC 9.4.3 is not readily available from windows-latest either (just as from ubuntu-20.04); so we'd need to add some manual tweaks to get it for CI
but that's for later
mikolaj
bgamari: ghc-pkg-9.4.2: cannot find package resolv: https://github.com/haskell/cabal/actions/runs/3634495918/jobs/6132628142
[Update GHC in CI from 9.4.2 to 9.4.3 and try to run it last · haskell/cabal@4cb2377](https://github.com/haskell/cabal/actions/runs/3634495918/jobs/6132628142) - GitHub
Official upstream development repository for Cabal and cabal-install - Update GHC in CI from 9.4.2 to 9.4.3 and try to run it last · haskell/cabal@4cb2377

but I don't think the

12program-options
  ghc-options: -fno-ignore-asserts -v3

did anything
bgamari@bgamari:matrix.org
ahh yes, you'll need to point ghc-pkg at cabal-install's package database
mikolaj
ok, where is the database?
and how to get -v3 to work?
bgamari@bgamari:matrix.org
given that this is a local package it will probably be in dist-newstyle
I'll admit, while I love cabal-v2, it has made GHC developers' lives harder for this reason
finding where cabal-install places build artifacts can be quite tricky
more than once I have had to rely on find and a bit of luck
oh, actually, is resolv a local package?
I think I may have been wrong
in which case the relevant package database is in the user's cabal store
$HOME/.cabal/store/...

regarding -v3 I generally use

12package *
     ghc-options: -v3

mikolaj
oh, not program-options? OK, let me try
program-options section apparently didn't work
bgamari@bgamari:matrix.org
yeah, it's quite unclear why program-options wouldn't work though
but you will also find that cabal build --ghc-options=... inexplicably doesn't work
this has also caught me by surprise more than once
mikolaj
for any options? or just v3?
bgamari@bgamari:matrix.org
anything
mikolaj
wow
quotation marks?
bgamari@bgamari:matrix.org
I think it's due to the same cause as https://github.com/haskell/cabal/issues/2997
[--extra-lib-dirs and --extra-include-dirs ignored? · Issue #2997 · haskell/cabal](https://github.com/haskell/cabal/issues/2997) - GitHub
I tried compiling hackage-server with new-build, and hackage-server relies on text-icu, which in my case is installed in the brew Cellar and hence needs additional lib and include paths. However, d...
IMHO these flags should be simply removed if they aren't supported since it's very easy to lose quite a bit of time to things like this
mikolaj
indeed
heh, oh yes, now -v3 works; CI slowed down to a crawl :D
bgamari@bgamari:matrix.org
heh
mikolaj
the out of ghc-pkg: https://github.com/haskell/cabal/actions/runs/3634604652/jobs/6132858557
[Update GHC in CI from 9.4.2 to 9.4.3 and try to run it last · haskell/cabal@4887021](https://github.com/haskell/cabal/actions/runs/3634604652/jobs/6132858557) - GitHub
Official upstream development repository for Cabal and cabal-install - Update GHC in CI from 9.4.2 to 9.4.3 and try to run it last · haskell/cabal@4887021
and at the bottom, the failure with -v3
though, somehow, -v3 seems only to affect the builds that did not fail
I think the script must have hidden the stderr output; let me override
bgamari@bgamari:matrix.org
hmm, indeed: extra-libraries:      resolv
mikolaj
this is supposedly more verbose, but I can't see a difference (still patchy, I guess?): https://github.com/haskell/cabal/actions/runs/3634604652/jobs/6132858557
[Update GHC in CI from 9.4.2 to 9.4.3 and try to run it last · haskell/cabal@4887021](https://github.com/haskell/cabal/actions/runs/3634604652/jobs/6132858557) - GitHub
Official upstream development repository for Cabal and cabal-install - Update GHC in CI from 9.4.2 to 9.4.3 and try to run it last · haskell/cabal@4887021
so, have you found and, more importantly, fixed the problem?
:D
bgamari@bgamari:matrix.org
sadly no
unless @artem is correct and the symbol has been moved 
but in that case I have no explanation for why this differs from my own build
unless github's image really does differ
is there any way I can bring up a container with github's image?
mikolaj
I'm clueless about docker
bgamari@bgamari:matrix.org
how does one replicate the GitHub Actions environment locally?
* bgamari (@bgamari:matrix.org) doesn't mind whether it's docker or otherwise
but I feel like trying to diagnose this via CI is going to more painful than necessary
mikolaj
IDK: https://github.com/nektos/act ?
[GitHub - nektos/act: Run your GitHub Actions locally 🚀](https://github.com/nektos/act) - GitHub
Run your GitHub Actions locally 🚀. Contribute to nektos/act development by creating an account on GitHub.
but most probably the problem lies in their image, right?
bgamari@bgamari:matrix.org
it's tough saying
mikolaj
but I suppose that tool installs the exact same image, too; and then runs from the .yml files
bgamari@bgamari:matrix.org
I mean, all we can likely conclude is that it differs somehow
mikolaj
which is fine --- it fails fast in this case
yeah, hard to guess
bgamari@bgamari:matrix.org
that's not to say it's necessarily wrong
I would really want to poke around at libc.so and libresolv.so and see which defines the symbol in question
then the question is why the configure check fails to discover this on its own
and, perhaps most importantly, how this differs from the official ubuntu image
mikolaj
bgamari: I'm about to drop, but at https://github.com/Mikolaj/cabal/pull/new/ci-latest-experiments are the hacks that made it show describe and partial v3 if that's helpful
[Build software better, together](https://github.com/Mikolaj/cabal/pull/new/ci-latest-experiments) - GitHub
GitHub is where people build software. More than 94 million people use GitHub to discover, fork, and contribute to over 330 million projects.
bgamari@bgamari:matrix.org
alright, I'm afraid I should really get back to GC things
* bgamari (@bgamari:matrix.org) is very late getting this patch to his client
it was good to have a distraction for a bit though
mikolaj
no rush, our tmp fix is brewing
haha
shall I open a cabal ticket and copy our coversation?
bgamari@bgamari:matrix.org
yes, I think that would be a good idea
mikolaj
I'm on it
thank you very much once again
* geekosaur (@geekosaur:libera.chat) has been wondering if it's something silly like a cached libHSresolv from 20.04 that works fine if built again on 22.04
bgamari@bgamari:matrix.org
no worries; have a good night
mikolaj

    * geekosaur (@geekosaur:libera.chat) has been wondering if it's something silly like a cached libHSresolv from 20.04 that works fine if built again on 22.04

a good question
mikolaj: what exactly are you caching?
mikolaj
a lot; yes, that's next on my list
let me add this to the ticket
bgamari@bgamari:matrix.org
yeah, definitely be certain you aren't caching across operating systems
mikolaj
I probably am
 will reset cache
bgamari@bgamari:matrix.org
better to be too conservative in your cache key than too liberal
mikolaj
no idea of ${{ runner.os }} contains version of ubuntu or only "ubuntu"
bgamari@bgamari:matrix.org
it may just contain "linux" for all I know
mikolaj
so that's likely broken
I will let you know if that gets it fixed

**Comment by Mikolaj** [comment]
It turns out resetting cache does not solve the problem: https://github.com/haskell/cabal/pull/8631

**Comment by andreasabel** [comment]
Unrelated, but also a transition problem from ubuntu-20.04 to ubuntu-22.04: 
- https://github.com/agda/agda/issues/6384

In our case it is that static linking works with `ubuntu-20.04` but no longer with `ubuntu-22.04`.

**Comment by ulysses4ever** [comment]
We're currently at ubuntu-22.04, so I assume this can be closed

https://github.com/haskell/cabal/blob/1082c0bb4e498fc9ea3b7b8cbfa78a99f2edb3b9/.github/workflows/validate.yml#L76
