### ISSUE TITLE
cabal-install-3.4.0.0-rc4 does not compile with ghc-9.0.1-alpha-1

### ISSUE THREAD

**Issue by peti** [haskell/cabal#7132]
According to https://build.opensuse.org/package/live_build_log/devel:languages:haskell:ghc-9.0.x/cabal-install/openSUSE_Tumbleweed/x86_64, the build fails with this error:

~~~
[   43s] Distribution/Client/Dependency/Types.hs:38:23: error:
[   43s]     parse error on input ‘->’
[   43s]    |
[   43s] 38 |             _         -> P.unexpected $ "PreSolver: " ++ name
[   43s]    |                       ^^
~~~~

**Comment by phadej** [comment]
I don't see anything wrong in https://github.com/haskell/cabal/blob/81fd8d935a25212d9b38c9b8b41fac2c22d42d58/cabal-install/Distribution/Client/Dependency/Types.hs#L33-L38

**Comment by phadej** [comment]
Also note that `cabal-install-3.4` is not officially buildable with GHC-9.0 at the moment.

**Comment by peti** [comment]
Maybe it's a bug in the compiler?

**Comment by phadej** [comment]
With `ghc-9.0` built from commit 90fe5cffb0b0ba1ff86b8b9bf5299d0ed8437ad7 I don't get that error when trying that module in isolation (commenting out the imports):

```
% /code/ghc/_build_ghc-9.0/stage1/bin/ghc -fforce-recomp Types.hs
[1 of 1] Compiling Distribution.Client.Dependency.Types ( Types.hs, Types.o )

Types.hs:18:43: error:
    Not in scope: type constructor or class ‘Generic’
   |
18 |   deriving (Eq, Ord, Show, Bounded, Enum, Generic)
   |                                           ^^^^^^^

Types.hs:22:43: error:
    Not in scope: type constructor or class ‘Generic’
   |
22 |   deriving (Eq, Ord, Show, Bounded, Enum, Generic)
   |                                           ^^^^^^^

Types.hs:24:10: error:
    Not in scope: type constructor or class ‘Binary’
   |
24 | instance Binary PreSolver
   |          ^^^^^^

Types.hs:25:10: error:
    Not in scope: type constructor or class ‘Binary’
   |
25 | instance Binary Solver
   |          ^^^^^^

Types.hs:27:10: error:
    Not in scope: type constructor or class ‘Structured’
   |
27 | instance Structured PreSolver
   |          ^^^^^^^^^^

Types.hs:28:10: error:
    Not in scope: type constructor or class ‘Structured’
   |
28 | instance Structured Solver
   |          ^^^^^^^^^^

Types.hs:30:10: error:
    Not in scope: type constructor or class ‘Pretty’
   |
30 | instance Pretty PreSolver where
   |          ^^^^^^

Types.hs:33:10: error:
    Not in scope: type constructor or class ‘Parsec’
   |
33 | instance Parsec PreSolver where
   |          ^^^^^^

Types.hs:35:17: error:
    Not in scope: ‘P.munch1’
    No module named ‘P’ is imported.
   |
35 |         name <- P.munch1 isAlpha
   |                 ^^^^^^^^

Types.hs:38:26: error:
    Not in scope: ‘P.unexpected’
    No module named ‘P’ is imported.
   |
38 |             _         -> P.unexpected $ "PreSolver: " ++ name
   |                          ^^^^^^^
```

**Comment by gbaz** [comment]
obsolete afaik?
