### ISSUE TITLE
`cabal-install` dependency on `network-uri` is too loose

### ISSUE THREAD

**Issue by mniip** [haskell/cabal#11229]
**Describe the bug**
`cabal-install` `3.14.2.0` and `3.16.0.0` build-depends on `network-uri >=2.6.0.2 && <2.7`, but fails to build with `network-uri` `2.6.0.2`, `2.6.0.3`, and `2.6.1.0`.

The reason being that `Distribution.Client.ProjectConfig.Legacy` uses `nullURIAuth` that was only added in `network-uri >=2.6.2.0`.

**To Reproduce**

```
$ cabal install cabal-install-3.14.2.0 --with-compiler ghc-9.6.7 --constraint 'network-uri ==2.6.0.2'
...
src/Distribution/Client/ProjectConfig/Legacy.hs:188:31: error:
    Module ‘Network.URI’ does not export ‘nullURIAuth’
    |
188 | import Network.URI (URI (..), nullURIAuth, parseURI)
    |                               ^^^^^^^^^^^
```

**Expected behavior**
Dependency bounds should exclude these configurations.

**Comment by geekosaur** [comment]
This makes me think someone typoed, since it's swapping two digits?

**Comment by geekosaur** [comment]
In fact, it's correct further down, so I'm voting for "typo". Patch incoming and will update bounds on Hackage.

**Comment by mniip** [comment]
The dependency on `nullURIAuth` was introduced much later than the `>=2.6.0.2` bound. `cabal-install` versons prior to 3.14 do build successfully against these `network` versions.

**Comment by geekosaur** [comment]
Right, but look at the bounds in the tests following the executable.

**Comment by geekosaur** [comment]
In any case, I've just updated the Hackage bounds for the 3.14 and 3.16 releases, and #11230 is in CI and waiting for reviews.
